### ISSUE TITLE
Unable to install mpic with conda

### ISSUE THREAD

**Issue by wenxuanou** [simonalexanderson/ListenDenoiseAction#1]
Hi!

I was trying to set up the environment for the code, but I could not get `mpic` package when running `conda install -c conda-forge mpi4py mpic` . I then checked the conda-forge repo and found out that there is no `mpic` pakcage under the conda-forge channel. 
![image](https://github.com/simonalexanderson/ListenDenoiseAction/assets/35703065/d0855979-7ee3-4309-8a61-665e1d86f50e)
Instead, there is a `mpich` package available. Should I install `mpich` instead of `mpic`?

In addition, after  `conda install -c conda-forge mpi4py`, conda automatically downloaded and installed python 3.11. Should the python version be 3.11 instead of 3.9?

**Comment by nagyrajmund** [comment]
Hi!

Yes, there was a typo in the README, the package is called `mpich`. Thanks for spotting this!

> In addition, after conda install -c conda-forge mpi4py, conda automatically downloaded and installed python 3.11. Should the python version be 3.11 instead of 3.9?

I couldn't reproduce this. The correct version is 3.9, but in principle 3.11 shouldn't cause a major problem.
