### ISSUE TITLE
Not generating motion

### ISSUE THREAD

**Issue by vtan05** [simonalexanderson/ListenDenoiseAction#3]
Hi,

When I run `./experiments/dance_LDA.sh`, the sliced wav forms can be seen in the results folder but the generated motion and rendered videos are missing. I just followed the instructions in the README. Is there something missing that I should install or download?

**Comment by simonalexanderson** [comment]
The output should be wav and BVH files. The bvh files contains the character motion data, but it needs to be rendered with some external software. For our presentation videos, I used Autodesk MotionBuilder to convert the data to fbx, and then rendered it in Unity. If you don't get any BVH files, please check the terminal log for errors.

**Comment by vtan05** [comment]
I finally figured it out. The following files in the data folder should be changed:
- dance_styles.txt -> dance_styles_kth.txt 
- dance_train_files.txt -> dance_train_files_kth.txt 
- dance_train_files.txt -> dance_test_files_kth.txt

**Comment by huzhongyyuan** [comment]
> I finally figured it out. The following files in the data folder should be changed:
> 
> * dance_styles.txt -> dance_styles_kth.txt
> * dance_train_files.txt -> dance_train_files_kth.txt
> * dance_train_files.txt -> dance_test_files_kth.txt

hello did you run the train code succcessfully？I wanna a detailed training instruction，much thanks
